import { Post, PostCategory, PostSubcategory } from '../models/post';

export const mockPosts: Post[] = [
  {
    id: 1354632462346,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 100342634262301,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 100024363246210001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 1000132463240002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1047324730010003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 10023473477010004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 223463653264234,
    title: 'Revolution Bike Park',
    subtitle: '@Santa Cruz',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-weekly.svg',
    comments: [
      {
        id: 223456234532000,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 20002032453245324001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 20002345632420002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 200032453220003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 20034532420004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 323453252,
    title: 'Revolution Bike Park',
    subtitle: '@BIKE PARK WALES',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 303245635200,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 3005234532476030001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 300043263263230002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 30002345324523300003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 3003245342532030004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 4321521352135,
    title: 'Revolution Bike Park',
    subtitle: '@BIKE PARK WALES - TRAILS 6',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 40213563200,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 4000213623640001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 4002136236040002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 40004213623160003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 4000123626140004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 5123623626,
    title: 'Revolution Bike Park',
    subtitle: 'CRANKWORKS',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-group.svg',
    comments: [
      {
        id: 50236162312600,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 5000123623650001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 50002136362150002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 50021362636050003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 50002136621350004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 6765765875,
    title: 'Revolution Bike Park',
    subtitle: 'KNUCKLE HUCK',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 6785657587500,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 6000675675860001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 600067657850002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 6007657685060003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 60005585560004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 765896758,
    title: 'Revolution Bike Park',
    subtitle: 'MASTER THE WHEEL',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-ridetime.svg',
    comments: [
      {
        id: 70567985750,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 7000765765795870001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 7000453546370002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 70007006879603,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 700765586757070004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 85796546589,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 876567845700,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 8007646794675080001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 800067478563654980002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 8000346578980003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 800088675943860004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 965795588,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-weekly.svg',
    comments: [
      {
        id: 9748567346700,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 9000744876990001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 90009674870002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 900076487690003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 900076587690004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1656795870,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 110659780,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 110765498011001,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 1100645748711002,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 11067547011003,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 1100978011004,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1657484591,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 100123515,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 100051256126,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10021215625611,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1002125151,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 10031251251251,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1125152,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-group.svg',
    comments: [
      {
        id: 1021515125210,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 100215112515120,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 105325325101,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 10125102,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 100234523453,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1243523,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 10234532450,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 1023455324500,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 1042352345201,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1043276347302,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 1007324732473,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 14432734,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-ridetime.svg',
    comments: [
      {
        id: 10423732720,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 10047327230,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10423743201,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 104327372402,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 1043272347703,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1432723475,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 104327234720,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 104237342732400,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 102374772701,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 105347347402,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 1034574573503,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 134564364566,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-weekly.svg',
    comments: [
      {
        id: 105437357350,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 104537453754700,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 100543845883681,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1043574352302,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 10345734383403,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 1435734784357,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 1043574340,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 10043574220,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10345745378401,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 10345754373402,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 18545388344003,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 456453645633458,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.LARGE,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    comments: [
      {
        id: 1032575634260,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 10023473273420,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10432737237401,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 100347324673242,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 104356346324403,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 14353262649,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-group.svg',
    comments: [
      {
        id: 10234624362630,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 10024362377340,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10047237324323471,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1002437272374732,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 1032477342743303,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 22347237437470,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-monthly.svg',
    comments: [
      {
        id: 1234663600,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 1032463246700,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 103246734701,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 1005435234532,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 10234642632603,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
  {
    id: 23426436341,
    title: 'Revolution Bike Park',
    subtitle: 'NEW WR',
    author: '@OLLY WILKINS',
    category: PostCategory.MEDIUM,
    subcategory: PostSubcategory.PARK,
    content:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    imageUrl: '',
    likes: 120,
    titleImageUrl: '/assets/podium-icons/podium-text-ridetime.svg',
    comments: [
      {
        id: 10234634632460,
        author: 'CommentAuthor1',
        date: new Date(),
        content: 'Comment 1',
        likes: 0,
        replies: [
          {
            id: 103246324656200,
            author: 'ReplyAuthor1',
            date: new Date(),
            content: 'Comment 1',
            likes: 1,
          },
          {
            id: 10432623632301,
            author: 'ReplyAuthor2',
            date: new Date(),
            content: 'Comment 2',
            likes: 2,
          },
          {
            id: 123463246242002,
            author: 'ReplyAuthor3',
            date: new Date(),
            content: 'Comment 3',
            likes: 3,
          },
          {
            id: 10234632643203,
            author: 'ReplyAuthor4',
            date: new Date(),
            content: 'Comment 4',
            likes: 4,
          },
        ],
      },
    ],
  } as Post,
];
